/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcmotors;

import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author Dhanushka
 */
public class DetailsStock extends javax.swing.JFrame {

    /**
     * Creates new form DetailsStock
     */
    public DetailsStock() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    //set all labels
    void setLabels(Stock stock) {
        lblStockID.setText(stock.getStockID());
        lblPartID.setText(stock.getPartID());
        lblPartType.setText(stock.getPartType());
        lblPartName.setText(stock.getPartName());
        lblPartModel.setText(stock.getPartModel());
        lblPartCost.setText(stock.getCost() + "");
        lblPartPrice.setText(stock.getPrice() + "");
        lblDiscount.setText(stock.getDiscount() + "");
        lblQuantity.setText(stock.getQuantity() + "");
        lblStock.setText(stock.getPartStock());
        lblDealerID.setText(stock.getDealerID());
        lblDealerName.setText(stock.getDealerName());
        lblDealerEmail.setText(stock.getDealerEmail());
        lblDealerContact.setText(stock.getDealerContact());
        lblAddedDate.setText(stock.getAddDate().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblStockID = new javax.swing.JLabel();
        lblPartID = new javax.swing.JLabel();
        lblPartType = new javax.swing.JLabel();
        lblPartName = new javax.swing.JLabel();
        lblPartModel = new javax.swing.JLabel();
        lblPartCost = new javax.swing.JLabel();
        lblPartPrice = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblDealerID = new javax.swing.JLabel();
        lblDealerName = new javax.swing.JLabel();
        lblDealerEmail = new javax.swing.JLabel();
        lblDealerContact = new javax.swing.JLabel();
        lblAddedDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 182, 182)), " stock details ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Stock ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Part ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Part Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Part Cost :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 80, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Part Price :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 80, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Discount :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Quantity :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Part Type :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Part Model :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Part Stock :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, -1));

        lblStockID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStockID.setText("stock id");
        jPanel1.add(lblStockID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, -1));

        lblPartID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPartID.setText("part id");
        jPanel1.add(lblPartID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, -1));

        lblPartType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPartType.setText("type");
        jPanel1.add(lblPartType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 240, -1));

        lblPartName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPartName.setText("name");
        jPanel1.add(lblPartName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, -1));

        lblPartModel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPartModel.setText("model");
        jPanel1.add(lblPartModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 240, -1));

        lblPartCost.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPartCost.setText("cost");
        jPanel1.add(lblPartCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 240, -1));

        lblPartPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPartPrice.setText("price");
        jPanel1.add(lblPartPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 240, -1));

        lblDiscount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDiscount.setText("discount");
        jPanel1.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 240, -1));

        lblQuantity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblQuantity.setText("quantity");
        jPanel1.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 240, -1));

        lblStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStock.setText("stock");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 760, 170));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jcmotors/main frame logo.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Dealer ID :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Dealer Name :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Dealer Email :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Dealer Contact :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Stock Added Date :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblDealerID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDealerID.setText("id");
        jPanel2.add(lblDealerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, -1));

        lblDealerName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDealerName.setText("name");
        jPanel2.add(lblDealerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, -1));

        lblDealerEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDealerEmail.setText("email");
        jPanel2.add(lblDealerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 240, -1));

        lblDealerContact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDealerContact.setText("contact");
        jPanel2.add(lblDealerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 240, -1));

        lblAddedDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddedDate.setText("added date");
        jPanel2.add(lblAddedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 240, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 390, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new HiFiLookAndFeel());
                } catch (Exception e) {
                }
                new DetailsStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddedDate;
    private javax.swing.JLabel lblDealerContact;
    private javax.swing.JLabel lblDealerEmail;
    private javax.swing.JLabel lblDealerID;
    private javax.swing.JLabel lblDealerName;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblPartCost;
    private javax.swing.JLabel lblPartID;
    private javax.swing.JLabel lblPartModel;
    private javax.swing.JLabel lblPartName;
    private javax.swing.JLabel lblPartPrice;
    private javax.swing.JLabel lblPartType;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblStockID;
    // End of variables declaration//GEN-END:variables
}
