/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jcmotors;

import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Dhanushka
 */
public class UpdatePart extends javax.swing.JFrame {

    DBOperations dbOps = new DBOperations();
    /**
     * Creates new form UpdatePart
     */
    public UpdatePart() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPartId = new javax.swing.JTextField();
        txtPartName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ddStock = new javax.swing.JComboBox();
        ddType = new javax.swing.JComboBox();
        ddModel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update A Part");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(182, 182, 182)), " update a part ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Part id");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Part Name");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Type");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Model");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        txtPartId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPartId.setEnabled(false);
        txtPartId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartIdActionPerformed(evt);
            }
        });
        jPanel5.add(txtPartId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 20));

        txtPartName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel5.add(txtPartName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 250, 20));

        btnUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 100, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Stock");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        ddStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ddStock.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Other", "Hero" }));
        jPanel5.add(ddStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 250, -1));

        ddType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ddType.setMaximumRowCount(5);
        ddType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Type 1", "Type 2", "Type 3", "Type 4", "Type 5" }));
        jPanel5.add(ddType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 250, -1));

        ddModel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ddModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Model 1", "Model 2", "Model 3", "Model 4", "Model 5", " " }));
        jPanel5.add(ddModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 250, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 370, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the values to the fields
     * @param part 
     */
    void setFields(Part part){
        txtPartId.setText(part.getId());
        txtPartName.setText(part.getName());
        ddStock.setSelectedItem(part.getStock());
    }
    
    private void txtPartIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartIdActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //create new Part and assign date
        Part part = new Part();
        part.setId(txtPartId.getText());
        part.setName(txtPartName.getText());
        part.setType(ddType.getSelectedItem().toString());
        part.setModel(ddModel.getSelectedItem().toString());
        part.setStock(ddStock.getSelectedItem().toString());

        //add above new part to the db
        boolean result = dbOps.updatePart(part);

        if (result) {
            JOptionPane.showMessageDialog(this, "Successfully Updated!");
            this.dispose(); //current window will disappear
        } else {
            JOptionPane.showMessageDialog(this, "Error occured!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new HiFiLookAndFeel());
                } catch (Exception e) {
                }
                new UpdatePart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox ddModel;
    private javax.swing.JComboBox ddStock;
    private javax.swing.JComboBox ddType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtPartId;
    private javax.swing.JTextField txtPartName;
    // End of variables declaration//GEN-END:variables
}
